# Generated by Django 5.0.7 on 2024-07-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cve', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('ultima_modificacion', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('nivel_complejidad', models.CharField(max_length=50)),
                ('estado_fixeado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
